export const conditioning = [
  "Start a sequence with Hip Key",
  "MeatHooks",
  "Do something from one foot lock",
  "30 Second Dead Hang",
  "Do the drop that scares you the most",
  "Invent something new... (carefully)",
  "Do a combo keeping the silks separated the whole time",
  "Find something to do in belay",
  "Do a combo keeping the silks together the entire time",
  "Strengthen your grip with one hand dead hangs",
  "Do your favorite 3-4 tricks together in a combo",
  "Find a fun transition in between your 2 favorite tricks",
  "Balance your splits... or work towards the ability to balance",
  "Do as many V-Ups as possible",
  "Lay on the Mat and Complain",
  "Do your Favorite Belay",
  "Hox Climbs",
  "Circus Climbs",
  "25 consecutive v-ups in the knot",
  "C-rolls in the knot (3 - in each direction)",
  "Skin the cat",
  "Pick a trick that has become mundane and find a way to add your own style",
  "Hand over hand climb",
  "Do 5 pull-ups",
  "Do 10 push-ups",
];
